### ISSUE TITLE
No user id

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/ApplicationInsights-aspnetcore#136]
I am using Azure AD with OpenId in my aspnet core application and noticed all properties on the `Context.User` from the `TelemetryClient` were null.

I tried creating middleware as such, but looking at the injected `TelemetryClient` instance on a controller has the id value back to null.
```c#
public class AddUserToTelemetry
{
    private RequestDelegate _next;
    private TelemetryClient _telemetryClient;

    public AddUserToTelemetry(RequestDelegate next, TelemetryClient telemetryClient)
    {
        _next = next;
        _telemetryClient = telemetryClient;
    }

    public async Task Invoke(HttpContext context)
    {
        var userEmail = context.User.FindFirst(ClaimTypes.Upn)?.Value ?? context.User.FindFirst(ClaimTypes.Email)?.Value;
        _telemetryClient.Context.User.Id = userEmail;

        await _next.Invoke(context);
    }
}
```

It seems as the injected `TelemetryClient` is being added by `AddScoped` for DI so I would've assumed this instance was the same and scoped to the request. Is there another way/guidance on setting user properties without having to do it in each controller?

**Comment by SergeyKanzhelev** [comment]
Something like this would work:

``` csharp
var request = context.RequestServices.GetService<RequestTelemetry>();
request.Context.User.Id = "value you need";
```

**Comment by SergeyKanzhelev** [comment]
This will associate requests with user context. For other types of telemetry you will need to implement telemetry initializer. Something similar to https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNet/TelemetryInitializers/WebUserTelemetryInitializer.cs Basically you have http context accessor and take user from it.

**Comment by damienpontifex** [comment]
Thanks @sergey-shandar 

I see the a custom telemetry initializer as a good way to go. My initial findings were to add it by this in my `Startup.Configure` method:

```c#
var contextAccessor = app.ApplicationServices.GetRequiredService<IHttpContextAccessor>();
TelemetryConfiguration.Active.TelemetryInitializers.Add(new UserTelemetryInitializer(contextAccessor));
```

But my overriden `OnInitializeTelemetry` method never seems to get called. 

In an aspnet core, wouldn't this more appropriately be configured on an extension after `services.AddApplicationInsightsTelemetry` in `Startup.ConfigureServices` so the `IHttpContextAccessor` can be injected and follow more similar patters as mvc add further options? Something like:

```c#
services.AddApplicationInsightsTelemetry(Configuration)
    .AddTelemetryInitializer<UserTelemetryInitializer>();
```

Or is there another way to add it in aspnet core other than the static `TelemetryConfiguration.Active`?

Thanks for the assistance.

**Comment by SergeyKanzhelev** [comment]
Don't use `TelemetryConfiguration.Active`, register initializers in DI before `EnableApplicationInsights` like we override the channel: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/test/Mvc6Framework45.FunctionalTests/Startup.cs#L44

Something like `services.AddInstance<ITelemetryInitializer>(new AddApplicationInsightsTelemetry());`

**Comment by damienpontifex** [comment]
I don't believe I could use `AddInstance` and new up the telemetry initializer as it requires `IHttpContextAccessor` as a parameter to the constructor.

Tried both
`services.AddTransient<ITelemetryInitializer, UserTelemetryInitializer>();`
`services.AddScoped<ITelemetryInitializer, UserTelemetryInitializer>();`

which helps and my `OnInitializeTelemetry` is called and I set the `User.Id` on the `ITelemetry` and `RequestTelemetry` instance that gets passed in there, but the injected `TelemetryClient` on my controller has `Context.User.Id` still as null.

**Comment by SergeyKanzhelev** [comment]
Yes, you are correct. We are using `AddSingleton` for telemetry initializers: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsExtensions.cs#L43

**Comment by TheXenocide** [comment]
I see what it is this is recommending, but I still don't understand *why* `TelemetryConfiguration.Active.TelemetryInitializers.Add` works for some telemetry, but not others? Why are we responsible for knowing the implementation details of how Application Insights is hooking into ASP.NET when AI provides its own extension points specifically designed for this? This prevents my code from being reusable between Web and non-Web projects. Unless I'm misunderstanding what's happening, I would consider it a bug that any telemetry is being sent without calling the actively configured initializers.

**Comment by SergeyKanzhelev** [comment]
@TheXenocide - it should be fixed with this PR: https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/256 @kartang, can you pls confirm?

**Comment by TheXenocide** [comment]
Cool. I think for now I can get by with ApplicationInsights.config if those are guaranteed to run on all telemetry tracking operations?

**Comment by SergeyKanzhelev** [comment]
We do not support ApplicationInsights.config with asp.net core

**Comment by SergeyKanzhelev** [comment]
Maybe you can expose `AddFoo` extension on services for asp.net core that will register all telemetry initializers you need.

**Comment by TheXenocide** [comment]
Ahhh, I see. So is this the same reason as to why TelemetryConfiguration.Active shouldn't be used? Either way, I feel like things that aren't supposed to be used with specific deployment profiles should at least be removed from PCLs/profile specific builds or perhaps at least marked Obsolete? It just doesn't seem obvious that this generic thing that exists and works as expected in most scenarios should be allowed to not work in one specific scenario without any feedback to the consumer? Regardless, I think I've found my solution for now, I'm just hoping to recommend more consistency in consumption.

**Comment by TheXenocide** [comment]
Apologies. It sounds like my original concern is already slated for resolution

**Comment by ohadschn** [comment]
@SergeyKanzhelev it looks like AI ASP.NET Core pulls configuration from multiple places:

1. `TelemetryConfiguration.Active` - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/ce6b4caade8566a451b3c98a10bc077d021f494f/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptions.cs#L21) (since 1.0.0-rc1-update4).
 1. `appsettings.json` - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/53ea997d23cef854bb05ccdf192199e818547dfe/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs#L31) (since 2.1.0-beta5).
 1. `AddApplicationInsightsTelemetry (ApplicationInsightsServiceOptions)` - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs) (since 2.0.0).
 1. `IServiceCollection` manipulation (usually `UseApplicationInsights`) - [source](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/1936d77d52df6dd4a868195b30ef17d9f5246579/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs).

It looks like 1-3 control simple properties like `InstrumentationKey` and `DeveloperMode` whereas 4 injects all the services and ignores whatever is set in `TelemetryConfiguration.Active.TelemetryInitializers`, `TelemetryModules.Instance.Modules`, `TelemetryConfiguration.Active.TelemetryProcessors`, and `TelemetryConfiguration.Active.TelemetryChannel`. 

Did I get it right? Could you please clarify exactly what configuration is taken from which place and what overrides what (I half guessed the order above)?

**Comment by SergeyKanzhelev** [comment]
@ohadschn you forgot the environment variables that will also be checked for the Azure Web Apps case mostly. We also have a standing PR https://github.com/Microsoft/ApplicationInsights-dotnet/pull/536 that I hesitant to accept as it will complicate the story even more.

Would you please create a separate issue for configuration story ironing/documenting.

**Comment by ohadschn** [comment]
@SergeyKanzhelev done: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/505.
