### ISSUE TITLE
Unable to open solution on "develop" branch

### ISSUE THREAD

**Issue by gzepeda** [Microsoft/ApplicationInsights-aspnetcore#191]
When downloading the latest version of the branch and trying to open it, I get the following error on Visual Studio when it loads the xproj files:

> Source\Repos\ApplicationInsights-aspnetcore1\src\Microsoft.ApplicationInsights.AspNetCore\Microsoft.ApplicationInsights.AspNetCore.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I do not have that "DotNet" folder under C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\. Am I missing an installation?

**Comment by kartang** [comment]
Hello, 

The develop branch is using CLI run time. You need to install dotnet CLI in order to build the project. We also need visual studio tools to support that. That is still in develop mode. Can you please checkout from master for now. We shall update the instructions about the runtime installations and visual studio tools to support CLI soon. 

Thanks

**Comment by gzepeda** [comment]
Sure thing. I will use master to send the changes for issue #23 

Thanks!
