### ISSUE TITLE
Implement synthetic traffic fileting from GSM

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-aspnetcore#23]
This will allow to mark synthetic traffic from availability tests https://azure.microsoft.com/en-us/documentation/articles/app-insights-monitor-web-app-availability/ with special flag "Synthetic Source"

We need to implement synthetic traffic filtering ```SyntheticTelemetryInitializer``` like we will have in 0.15 SDK for old-style web applications:

If header ```GsmSyntheticTestRunId``` present in request - set 
- ```telemetry.Context.Operation.SyntheticSource``` to ```Application Insights Availability Monitoring```
- ```telemetry.Context.User.Id``` to the value of the header ```SyntheticTest-Location``` 
- ```telemetry.Context.Session.Id``` to the value of the header ```SyntheticTest-RunId```

**Comment by gzepeda** [comment]
We already have a solution for this issue, but in order to create a pull request, I needed to open the project in the "Develop" branch, commit the changes there and send the pull request. 

As explained by @kartang here in #191, that is currently not possible. 

Master is too far behind right now compared to CLI and Develop as I can see, so I don't think doing the pull request from there is advisable. 

Please let us know what path we should follow or if we should wait until we can open and compile the "develop" branch and use it.

**Comment by kartang** [comment]
Closing this issue, as the changes have been made and the process to merge from masterRC1 (with gsm changes) to master is being tracked by https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/217.

**Comment by ohadschn** [comment]
Is this the ASP.NET Core equivalent of `Microsoft.ApplicationInsights.Web.SyntheticUserAgentTelemetryInitializer`?

If so, shouldn't it be `public` to allow usage via code (`TelemetryConfiguration.Active.TelemetryInitializers.Add(new SyntheticTelemetryInitializer());`)?
