### ISSUE TITLE
Could not load type Microsoft.ApplicationInsights.Extensibility.IContextInitializer from assembly 'Microsoft.ApplicationInsights

### ISSUE THREAD

**Issue by alextochetto** [Microsoft/ApplicationInsights-aspnetcore#235]
At the ConfigurationServices middleware of RC1-Update2 throw this exception for me at
services.AddApplicationInsightsTelemetry(Configuration);

I have the ApplicationInsights referenced in a Class Library and this Class Library is referenced at the WebApi project.

**Comment by dnduffy** [comment]
IContextInitializer was removed from the Microsoft.ApplicationInsights core SDK in 2.0.0-beta2.
 You appear to have mismatched assembly versions if you are trying to use 2.1.0 of the core SDK along with RC1 of AspNetCore. Now that ASP.NET Core 1.0.0 has shipped we no longer support DNX and older RC's from the ASP.NET team (because they don't support them).
You can try removing the IContextInitializer references or downgrade the version of the core Microsoft.ApplicationInsights SDK to the version that the RC1 bits of Microsoft.ApplicationInsights.AspNetCore are referencing.  However, using the outdated release candidates that aligned with the outdated RC's of ASP.NET itself is not supported.
What is blocking you from updating to .NET Core and 1.0.0?

**Comment by alextochetto** [comment]
@dnduffy it´s dificult to make many changes in a big project.
Some classes changed the namespace, for example XmlRoot now is at System.Xml.XmlSerializer.
TimeZoneInfo.ConvertTimeFromUtc doesn´t exists anymore.
Where is SHA1Managed and RijndaelManaged.
:(

**Comment by kartang** [comment]
@alextochetto It is highly recommended to upgrade the package (along with Asp.NET) to 1.0.0, as RC1 bits might have several features that are no more supported or might miss additional features that are available in the latest packages. 

However, for  the issue that you have with respect to contextInitializer, can you please try to upgrade the package to "**1.0.0-RC1-Update4**" and see if that works? That specific package uses **2.1.0-beta3** of **Microsoft.ApplicationInsights**. 

> Note: Please remove existing "Microsoft.ApplicationInsights" reference, and then upgrade "Microsoft.ApplicationInsights.AspNet".

Thanks!

**Comment by dnduffy** [comment]
@alextochetto I understand the cost of upgrading when namespaces change, we had to go through that in our SDK when ASP.NET changed their namespaces.
Unfortunately it will only get harder the longer you wait.  A lot of the namespace stuff is actually quite easy, you can just do two search and replace calls to get 90%.
I used [this blog](http://www.c-sharpcorner.com/article/converting-Asp-Net-5-beta-8-app-to-Asp-Net-core-rc2/) to help me do a similar upgrade.  I also created a new .NET Core project and looked at the changes in the project.json file vs. what I had previously.

**Comment by alextochetto** [comment]
@dnduffy I have already created a new project with update 3 of vs 2015 and instalation guid of .net core 1.0. It´s easier then change many things in an existent project.
I'll try with your sugestion to the blog, I guess will help in somethings.
Thanks a lot
Regards
