### ISSUE TITLE
Exceptions not logged when using ExceptionFilterAttribute

### ISSUE THREAD

**Issue by DDtMM** [microsoft/ApplicationInsights-aspnetcore#289]
When an `ExceptionFilter` is added as a filter to the MVC service, exception logging no longer works.  When I remove the filter everything works fine.  I even created a handler with `app.UseExceptionHandler` that does pretty much the same thing as the filter and it works fine.

My guess there isn't much you can do about this except warn people in the documentation and using TelemetryClient in the filter to log the exception.

*ConfigureServices*
 ```
 services.AddMvc(opts =>
{
  opts.Filters.Add(typeof(SanitizedExceptionFilterAttribute));
});
```

*SanitizedExceptionFilterAttribute*
```
public class SanitizedExceptionFilterAttribute : ExceptionFilterAttribute
{

    public override void OnException(ExceptionContext context)
    {
        var exInfo = new ExceptionInfo(context.Exception);
            
        context.Result =  new ObjectResult(exInfo);
        context.HttpContext.Response.StatusCode = 500;
    }
}
```

**Comment by DamianEdwards** [comment]
This is due to the fact that Application Insights is only tracking request exceptions, so any exception that doesn't propagate all the way back through the request stack will not be seen. The `ExceptionFilter` essentially handles the exception, so the request itself doesn't fault.

However, Application Insights could still track this using the new approach in 2.0.0-beta1 by wiring up a `DiganosticSourceListener` to the MVC event ["Microsoft.AspNetCore.Mvc.BeforeOnException"](https://github.com/aspnet/Mvc/blob/760c8f38678118734399c58c2dac981ea6e47046/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreDiagnosticSourceExtensions.cs#L276) and tracking an `ExceptionTelemetry` when that happens.

We'd likely want to make this optional behind a property on `ApplicationInsightsServiceOptions`, e.g. `EnableMvcExceptionTracking`, and potentially auto-de-dupe them with request exceptions in the case the exception isn't handled in the MVC action/filter pipeline.

@pakrym

**Comment by gjsduarte** [comment]
@DamianEdwards Any chance we could get example for this?

**Comment by taspeotis** [comment]
We're not using `ExceptionFilter`s, but we are using `UseExceptionHandler`. This seems to swallow all the exceptions.

I did note that [`ExceptionHandlerMiddleware` logs `Microsoft.AspNetCore.Diagnostics.HandledException`](https://github.com/aspnet/Diagnostics/blob/3a868d87a2458fd025ca71e2538b3a72f67c7c50/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L79). I'm not sure whether this event is any better than `BeforeOnException(Async)`.

So this appears to do what you'd expect if you call it from `Startup.Configure`:

```
public static class DiagnosticListenerExtensions
{
    public static void UseExceptionDiagnosticListener(this DiagnosticListener diagnosticListener)
    {
        diagnosticListener.SubscribeWithAdapter(new ExceptionDiagnosticListener());
    }

    private sealed class ExceptionDiagnosticListener
    {
        [DiagnosticName("Microsoft.AspNetCore.Diagnostics.HandledException")]
        public void OnDiagnosticHandledException(HttpContext httpContext, Exception exception)
        {
            Utils.LogExceptionEvent(exception);
        }
    }
}
```

Where `LogExceptionEvent` logs the exception to a `static` `TelemetryClient`. Although I couldn't work out if there's any way to use `HttpContext` to provide more correlation?

**Comment by cijothomas** [comment]
Closing this issue. With new Ilogger enablement by default, exceptions are automatically reported by application insights.
