### ISSUE TITLE
Read version information from project.json

### ISSUE THREAD

**Issue by rinatkar** [Microsoft/ApplicationInsights-aspnetcore#29]
Implement telemetry initializer that populates ```telemetry.Component.Version``` to the value read from project.json. 
This was blocked before by the issue in Configuration package. More details: https://github.com/aspnet/Configuration/issues/115

**Comment by gzepeda** [comment]
One question, should the project.json file be loaded as a Configuration File on ASP.NET Core 1 using a ConfigurationBuilder or should it be loaded in a different way?

Trying to figure out the best way to load the file and get the config information from it.

**Comment by SergeyKanzhelev** [comment]
Are there any other options how to load it? Will `ConfigurationBuilder` require a new dependency for the package?

**Comment by SergeyKanzhelev** [comment]
I don't see problems with `ConfigurationBuilder`

**Comment by kartang** [comment]
I don't think we need to explicitly load project.json. We need to make sure that "appsettings.json" is loaded, which contains the instrumentation key.

**Comment by gzepeda** [comment]
I will try ConfigurationBuilder then. Just need to add an additional nuget to the project: Microsoft.Extensions.Configuration.Json. 

Does the appsettings.json contain version info?

**Comment by kartang** [comment]
I am sorry for the confusion. I got the question wrong. No, appsettings will not contain the version info.

**Comment by xperiandri** [comment]
Does this work without any configuration? Or I need to set up this to work?

**Comment by SergeyKanzhelev** [comment]
It should work out of the box. Do you see otherwise?

Here are the pointers in code if it would help: [reading](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/9287d7e9e900f6a398c5f2b65fb2982302fd48d1/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L263) and [setting](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/ce6b4caade8566a451b3c98a10bc077d021f494f/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ComponentVersionTelemetryInitializer.cs#L11)
