### ISSUE TITLE
How to disable output into Visual Studio debug output tool window?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/ApplicationInsights-aspnetcore#328]
I don't need these messages as the all go to Diagnostics Tools tool window

**Comment by SergeyKanzhelev** [comment]
CC: @gardnerjr 

Currently diagnostics tools windows takes Application Insights events from the debug output window. So you may want to keep those.

Anyway - https://github.com/Microsoft/ApplicationInsights-dotnet/issues/310 if you still want to disable it

**Comment by gardnerjr** [comment]
@xperiandri do you just want the ability to "hide" them in the output window?  i'd prototype'd adding support for that once to the VS output window but we never prioritized it.  

If you make them not show up in the output window via @SergeyKanzhelev's link, then they won't show up in diagnostic tools either (we read them from the output window and "convert" them from "program output" to our own formatted items in diagnostic tools.

**Comment by xperiandri** [comment]
Yes
Them make a lot of noise which hides really importants log records.
I think that displaying application insights log entries within `Diagnostics Tools` tool window will be just enough.

**Comment by xperiandri** [comment]
I work with SignalR now and it receives a keep alive message from client every few seconds (some short period) so I only can see application insights logs with keep alive messages which hide everything else

**Comment by gardnerjr** [comment]
you could write a telemetry processor that throws those keepalive messages away. then, not only are they not in your output, they're not being sent to your AI resource and wasting time/money there too?

**Comment by xperiandri** [comment]
Agree. Where to have a look of cow to write a processor?

**Comment by gardnerjr** [comment]
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling has information about how to write those.

**Comment by dguisinger** [comment]
I really don't understand why the end developer needs to write some sort of a filter?  The fact is I rip telemetry out of every web app I build because I **NEED** to be able to look quickly at my debug output window to look at log events while I'm testing.  This telemetry output is obnoxious.  No one asked for this "feature"

**Comment by gardnerjr** [comment]
@dguisinger maybe you didn't ask for this feature, but many people did, and use it every day.  some people find that using telemetry to track down issues in production is more effective than just log output while debugging.  And like above shows, there are many options for silencing telemetry debug output entirely, or filtering out the things you don't need.

**Comment by dguisinger** [comment]
@gardnerjr I don't disagree that telemetry is a good thing, but why on earth do I, the end developer, someone who's trying to get something done, have to come up with a solution to get it out of my "Show output from Debug screen" when I never asked for all the random lines of JSON to be there in the first place?

Visual studio has a button to get rid of things like module load/unload messages.   There is no button to get rid of the lines that say "Application Insights Telemetry", and you may say I can go find a tool to do that, but I shouldn't have to, and that is my point.

Either telemetry needs the ability to not fill my output screen with garbage, or visual studio needs a built in way to filter it out seeing you install it on a project by default.  The middle ground of "its just there, deal with it" is not a friendly solution; which is why I just remove the whole thing from my projects.

**Comment by Quackmatic** [comment]
This is still a problem one year on. I have a large ASP.NET MVC solution with several projects running at once. It's impossible to read any debug messages or stack traces in the Output window because it is being spammed with JSON output several times per second.

Could a filter perhaps be added to get rid of this useless information? I'd rather not have to make a configuration change *in code* every time I switch feature branch just to stop the flood of console output.

**Comment by xperiandri** [comment]
`Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryDebugWriter.IsTracingDisabled = true;`

**Comment by EnCey** [comment]
@gardnerjr I believe everyone likes telemetry in the Application Insights Search view, but I seriously doubt anyone appreciates an endless barrage of tersely formatted JSON in their Debug Output Window.
