### ISSUE TITLE
Concern about the use of IHttpContextAccessor and potential perf impact

### ISSUE THREAD

**Issue by joechiu-msft** [Microsoft/ApplicationInsights-aspnetcore#349]
AI aspnetcore SDK injects about 9 telemetry initializers that all use IHttpContextAccessor to access headers and other information. [Discussions ](https://github.com/aspnet/Hosting/issues/793) in asp.net core repo indicates that there are meaningful perf impact when IHttpContextAccessor is used. 

What's your thought on IHttpContextAccessor and its perf impact to the overall consuming services? And do you have any plan around this that is perhaps more performant? Would it be possible for the AI middleware to extract information relevant to telemetry initializers and put them in a request scoped storage that can be consumed by the initializers?

From the referenced discussion, Identity is an example that will also bring in IHttpContextAccessor. The cost of IHttpContextAccessor is just part of the cost of using Identity. I think AI or telemetry in general is a more fundamental part of any asp.net core services, so much so that it's part of the default code template, therefore, I think AI may need a better answer in this regard.

**Comment by pharring** [comment]
The original motivation for not registering ```IHttpContextAccessor``` by default in ASP.NET Core was for improving throughput benchmarks. Setting the ```HttpContext``` on every call showed up in profiles because it allocates a new ```Dictionary``` on every call, so they decided it could be avoided.

Thankfully, I believe the major performance bottleneck of updating an ```AsyncLocal<T>``` on each request (that ```Dictionary``` allocation) has subsequently been largely mitigated via https://github.com/dotnet/coreclr/pull/8216

Also note that, in addition to Identity, MVC also brings in ```IHttpContextAccessor```, so it's quite hard to avoid. Otherwise, the implementation is about as trivial as you can imagine.

Now, perhaps accessing the ```AyncLocal``` ~9 times (once for each of registerd initializers) could be reduced to just once. For that, we'd need to redesign the way these telemetry initializers are registered. But really, we need performance data before we do that.  I'm confident there are lower hanging fruit in the Application Insights code.

**Comment by joechiu-msft** [comment]
Good to know about the improvements done to AsyncLocal. 

Would love to see your performance priorities shared in the Wiki. It helps us know what you already know to be an issue and what / how you prioritize. 

For the telemetry initializers, I think it would be better to align with asp.net core's pay per play paradigm. We are doing a stateless REST service on Azure service fabric, and at least 5 out of the 9 initializers are not applicable to us. We remove them in our service startup, but the initializers are internal classes, so we have to remove them by type name strings, not ideal.

**Comment by joechiu-msft** [comment]
And @pharring - question, you mentioned that MVC may also have brought in IHttpContextAccessor, although when I search its code base on GitHub, IHttpContextAccessor did not come up. There are some hits in the test code, that's it. Could you give a bit more pointer on that so we can pursue that lead?

**Comment by pharring** [comment]
Ah, my bad. You're right. All the hits are in test code.

**Comment by SergeyKanzhelev** [comment]
We will be posting performance numbers when we will have them.
