### ISSUE TITLE
TelemetryInitializerBase is internal

### ISSUE THREAD

**Issue by buuminh** [Microsoft/ApplicationInsights-aspnetcore#351]
Commit https://github.com/Microsoft/ApplicationInsights-aspnetcore/commit/b7db1a4940e715bd4081fdb4e1dde92592eff0f7 made the TelemetryInitializerBase internal. Was it really the intent? Isn't the purpose of this class to be reused to easily access the HttpContext from the request in a custom TelemetryInitilizer?

The other initializers are also internal, which would prevent from using them...

**Comment by pharring** [comment]
@pakrym, since he made the commit. Did we intend to hide them? For contrast, the initializers in the ApplicationInsights-dotnet-server repo are public and so is the ```WebTelemetryInitializerBase```.

**Comment by pakrym** [comment]
@pharring our goal was to shrink public API surface so we can change things without breaking changes to public API's. Accessing current `HttpContext` can pretty easily be done with `IHttpContextAccessor`

**Comment by pharring** [comment]
Thanks. It's very reasonable to limit the public surface area, especially early on.
Agreed that getting the current ```HttpContext``` is straightforward.

I think folks are being surprised to find that the derived initializers are also internal (#346 and one other I can't find right now). Right now, it's "all or nothing": i.e. You can call ```AddApplicationInsightsTelemetry``` and get our curated set of initializers; or, if you want a customized subset, then you're left re-implementing our list.

I recommend we monitor the feedback on this one and find out which initializers folks would really like to make public.

**Comment by bragma** [comment]
Hi @pharring,
I'm not so sure getting the current HttpContext is straightforward. I had to reimplement something similar to [TelemetryInitializerBase](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs) since it requires a lock. Nothing overly complex, but considering current documentation does not make any mention, I am still confused on the correct implementation.
