### ISSUE TITLE
Duplicate or incorrect logger provider registered in ASP.NET Core 2 due to light-up features.

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/ApplicationInsights-aspnetcore#579]
The light-up features in Visual Studio always configure AppInsights when running locally.
This results in an additional logger provider that is not configured with the settings I specify in `AddApplicationInsightsTelemetry()`.

## Repro Steps
1. Program.cs:
``` c#
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        // No WebHost.CreateDefaultBuilder() to keep the configuration as simple as possbile.
        public static IWebHost BuildWebHost(string[] args) =>
            new WebHostBuilder()
                .UseKestrel()
                .UseStartup<Startup>()
                .Build();
    }
```
2. Startup.cs
``` c#
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry(opt => opt.EnableDebugLogger = false);
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory factory)
        {
            // factory._providerRegistrations should have no registrations at this point, but has one.
            // This means that traces will still be logged in debug mode, even though EnableDebugLogger == false.
            //
            // opt.EnableDebugLogger = true (the default), would result in 2 registrations.
        }
    }
```

##  Actual Behavior
Traces are logged, even though `EnableDebugLogger == false`.

## Expected Behavior
Traces are not logged.

## Version Info 
SDK Version : 2.2.0-beta2
.NET Version : ASP.NET Core 2.0.3
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS 15.5.2
OS : Windows 10 Pro (1709)
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel console

**Comment by nphmuller** [comment]
Additional info: I'm using Serilog to configure all my logging. Because of this issue all the traces are logged twice. Once through the light-up AppInsights logger and once through my Serilog sink.

**Comment by SergeyKanzhelev** [comment]
@cijothomas can you help here?

**Comment by glennc** [comment]
I don't know that I am completely following the issue here, but there are some things can you can do.

1. the `ASPNETCORE_PREVENTHOSTINGSTARTUP` env var being set to 1 will disable all lightup. If you aren't using lightup at all then you can set that to disable it completely and rely solely on your own registration code.
2. In 2.1 we will add more fine grained control, to be able to just turn off specific parts of lightup.
3. I think there is a method on the logger factory that will let you clear all the providers and start again, removing anything that was added and starting with a clean slate.

Now that those options are there, let me see if I can understand what the actual issue is. If I read this correctly you are using Serilog, so don't want any of our stuff logging to App Insights directly. Are you setting an ikey and logging to an actual app insights instance or is this just in VS debug mode?

I am asking because this code stops us from adding a logger if that property is set: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/f696dd44f55055fad1774154219acf6c1e32c99b/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsInitializer.cs#L32

And this code stops us from double registering services: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/f696dd44f55055fad1774154219acf6c1e32c99b/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L127

So I want to make sure I understand what you are really seeing and what the issues here. Is it double logs to the App Insights resource or is it that you see stuff in the VS experience as well as Serilog or what. Does that make sense?

**Comment by nphmuller** [comment]
Sorry for the late response. I totally missed the notification.

The issue only occurs for me when running locally in VS during debugging.

My use case is that I want the code during development to be as close to production as possible. This includes Serilog logging the traces to AppInsights debug session telemetry, instead of the AppInsights logger.

The easiest way to accomplish this seemed setting `EnableDebugLogger` to false, like in my original post.
But when I do this, traces are still logged to the VS debug session telemetry. My instrumentation key is an empty string ("") in local debug mode, btw.

In my original post I probably made some assumptions which aren't true (the stuff about the provider registration count), so feel free to ignore that. :)

As a work around I set `ASPNETCORE_PREVENTHOSTINGSTARTUP` to true a while ago. But this also prevents other light-up features, which I don't necessarily want.

> 3 I think there is a method on the logger factory that will let you clear all the providers and start again, removing anything that was added and starting with a clean slate.

This seems like a better workaround to me than to disable all light-up features. Any idea what method this is? Because I can't find it.

> So I want to make sure I understand what you are really seeing and what the issues here. Is it double logs to the App Insights resource or is it that you see stuff in the VS experience as well as Serilog or what. Does that make sense?

I'm seeing duplicate trace logs in Visual Studio during debugging. Both in the `Application Insights Search` window (set to `Data from Debug session telemetry`) and in the `Event` tab of the `Diagnostic Tools`

**Comment by cijothomas** [comment]
@glennc Do we support this (turning off specific parts of lightup - application insights in this context) now in latest VS ?
_In 2.1 we will add more fine grained control, to be able to just turn off specific parts of lightup._

**Comment by glennc** [comment]
@cijothomas Yes, we added a something for it though I struggled to find any docs when I searched just now. Looks like the config key is "hostingStartupExcludeAssemblies". See: https://github.com/aspnet/Hosting/blob/e892ed8bbdcd25a0dafc1850033398dc57f65fe1/src/Microsoft.AspNetCore.Hosting/Internal/WebHostOptions.cs#L74

Sorry I don't have any better docs that go walk through it.

**Comment by cijothomas** [comment]
![image](https://user-images.githubusercontent.com/5232798/54289957-5c0fd400-4567-11e9-8c91-006add34dd1e.png)
recent VS has an option to turn off automatic appliation insights lightup. closing this issue.
