### ISSUE TITLE
Dependency Error Tracking

### ISSUE THREAD

**Issue by louislewis2** [Microsoft/ApplicationInsights-aspnetcore#625]
Hi,

I am using Application Insights, which is mostly a great experience :)
I have a question though around dependency tracking, by default
most of the "automatic" tracking works great.

How it determines failures, however is where I am stuck.
For example I am calling a REST endpoint, for an operation.
The fact that it returns a 200 response, does not mean that is was successful.

After I deserialize the response, I can then see that there was an error on their end.

How can I without disrupting the rest of the automatic tracking, but still flag this as
an error for the call?

A second question I have, is that we are batching calls to a few third party services.
Using Parallel.Foreach we either perform the REST or WCF calls. Again, how best would I implement the error tracking in this scenario?

I can see in the SDK, there is a call to track dependencies. I am unsure how it would work, if
I do it manually and what then happens to the automatic tracking?

**Comment by zakimaksyutov** [comment]
The scenario of changing parameters on automatically discovered dependency makes perfect sense! @lmolkova / @SergeyKanzhelev / @Dmitry-Matveev , what's the guidance for this case?

Re: Parallel.Foreach. What's the expected goal? My understanding is that AI SDK should automatically track all REST and WCF calls. Isn't it happening?

**Comment by cijothomas** [comment]
@louislewis2 Dependency Collector automatic collection determines success/failure based on response code. But you can override its behavior by writing custom logic in a TelemetryInitializer. See example here:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer

**Comment by louislewis2** [comment]
Hi @lmolkova 

Thank you for you detailed response.

I totally agree with you, that by following REST principles that it is not recommended to embed errors
into a 200 response. However this is the real word, and not all implementations follow these good practices. In our case, we are dealing with a third party provider and their implementation is out of our control. 

Seeing that you do not support this entirely, how best would I go about disabling the "auto" monitoring totally and then trust on my own implementation with the Application Insights Client? I would hope that this is possible on a per "Uri" instance and that its not a either on or off case. You clarity hear would be appreciated.

With the WCF, I would have to implement this also by disabling the "auto" tracking and implement this myself with the client. The same question above, applies here about disabling this "auto" tracking.

The above is however irrelevant if as you say, if I were to call track error and it would associate that with the telemetry, I can certain work with this if it works like this.

My question with the Parallel.Foreach is mainly how best to work withe the Application Insights Client.
Should I be creating a new instance in each iteration, thus tracking errors per call essentially. This would be super. My hesitance with implementing it this way in the first place, is just how the system sends those errors, if they too are batched or if they are sent once the client disposes.

**Comment by lmolkova** [comment]
@louislewis2 

# Tracking error separately from dependency
This is the most simple approach, here is an example:

```csharp
var responseMessage = await httpClient.GetAsync("https://www.microsoft.com/error");
var response = await responseMessage.Content.ReadAsStringAsync();
if (response.Contains("error"))
     telemetryClient.TrackEvent("error from microsoft.com");
```


Pros: 
- simple configuration and implementation

Cons:
- Event would be associated with the request telemetry rather than with dependency, i.e. would not be reliable with multiple dependency calls/retries. Considering your parallel foreach use case I assume it would work for you only if you are able to extend the event with something uniquely identifying particular dependency: url/number of retry/etc...


You may also manually (a bit hacky) correct the correlation details on the telemetry to make sure event belongs to particular dependency call:

```csharp
var responseMessage = await httpClient.GetAsync("https://www.microsoft.com/error");
var response = await responseMessage.Content.ReadAsStringAsync();
if (response.Contains("error"))
{
    EventTelemetry eventTelemetry = new EventTelemetry("error from microsoft.com");
    eventTelemetry.Context.Operation.Id = Activity.Current?.RootId;
    eventTelemetry.Context.Operation.ParentId = responseMessage.RequestMessage.Headers.GetValues("Request-Id").FirstOrDefault();
    telemetryClient.TrackEvent(eventTelemetry);
}
```

Pros: 
- simple and associates event with the error with particular depednency

Cons
- if we'd ever change "Request-Id" header name/syntax, it would stop working. We'll likely do that sometime in future with some deprecation period
- we may add some extensibility points that would not be invoked for such event with 'corrected' properties

# Manually tracking dependency
Another option is manual tracking. This is the cleanest approach, supported by the UI.
 This approach is similar for WCF and Http dependencies. You may want to alter DepednencyType for WCF ("WCF" instead of "Http")

```csharp
var url = new Uri("https://www.microsoft.com/error");
var request = new HttpRequestMessage(HttpMethod.Get, url);

DependencyTelemetry dependency = new DependencyTelemetry("Http", url.Host, $"{request.Method.Method} {url.AbsolutePath}", url.OriginalString);
using (telemetryClient.StartOperation(dependency))
{
    var responseMessage = await httpClient.SendAsync(request);
    var response = await responseMessage.Content.ReadAsStringAsync();
    if (response.Contains("error"))
    {
        dependency.Success = false;
        dependency.ResultCode = "My error description or code";
    }
}
```

# Disabling tracking dependencies for a particular endpoint

1. Implement `ITelemetryProcessor`

```csharp
public class DependencyFilterProcessor : ITelemetryProcessor
{
    private readonly ITelemetryProcessor next;

    public DependencyFilterProcessor(ITelemetryProcessor next)
    {
        this.next = next;
    }

    public void Process(ITelemetry item)
    {
        if (item is DependencyTelemetry dependency
            && dependency.Context.GetInternalContext().SdkVersion.StartsWith("rdd") // skip telemetry reported by the SDK automatically                
            && dependency.Data.Contains("microsoft.com")) // only for microsoft endpoint, you may filter based on full Url here
        {
            return;
        }

        this.next.Process(item);
    }
}
```

2. configure it:

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env, TelemetryConfiguration configuration)
{
    configuration.TelemetryProcessorChainBuilder.Use(next => new DependencyFilterProcessor(next));
    configuration.TelemetryProcessorChainBuilder.Build();
    // ...
}
```

In ASP.NET classic AppInsights SDK, use `TelemetryConfiguration.Active.TelemetryProcessorChainBuilder` as described [here](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling)

# Disable dependency tracking completely (for all kinds of auto tracked dependencies)

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();
    var telemetryModules =
        services.Where(m => m.ServiceType == typeof(ITelemetryModule));

    var dependencyTrackingTelemetryModule =
        telemetryModules.FirstOrDefault(
            m => m.ImplementationFactory?.Method?.ReturnType == typeof(DependencyTrackingTelemetryModule) ||
                    m.ImplementationType == typeof(DependencyTrackingTelemetryModule));

    if (dependencyTrackingTelemetryModule != null)
    {
        services.Remove(dependencyTrackingTelemetryModule);
        ((DependencyTrackingTelemetryModule) dependencyTrackingTelemetryModule.ImplementationInstance)?.Dispose();
    }
}
```

# Parallel foreach
I believe [this article](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking#parallel-operations-processing-and-tracking) gives extensive info on parallel processing.
If you use SDK-based tracking - it just works.
With manual instrumentation, make sure you isolate processing of each operation and tracking in `async Task` method. i.e.

```csharp
private async Task CallDependency()
{
    var url = new Uri("https://www.microsoft.com/error");
    var request = new HttpRequestMessage(HttpMethod.Get, url);

    DependencyTelemetry dependency = new DependencyTelemetry("Http", url.Host, $" 
                    {request.Method.Method} {url.AbsolutePath}", url.OriginalString);
    using (telemetryClient.StartOperation(dependency))
   {
       var responseMessage = await httpClient.SendAsync(request);
       var response = await responseMessage.Content.ReadAsStringAsync();
       if (response.Contains("error"))
       {
           dependency.Success = false;
           dependency.ResultCode = "My error description or code";
       }
   }
}
```

And use `Task.WhenAll` \ `Task.WhenAny` to process and await them.

**Comment by louislewis2** [comment]
@lmolkova Hi, wow that is the best response I could ever have asked for.
All my questions are perfectly answered, thank you very much for your effort.
