### ISSUE TITLE
AddApplicationInsightsTelemetry(this IServiceCollection services, IConfiguration config) overload does not set TelemetryClient.Active

### ISSUE THREAD

**Issue by zippy1981** [Microsoft/ApplicationInsights-aspnetcore#694]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps

1. Create an ASP.NET Core app with application insights
1. Set `ApplicationInsights:InstrumentationKey` to your instrumentation key
1. In Startup.cs do the following:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddApplicationInsightsTelemetry();

##  Actual Behavior

`TelemetryConfiguration.Active.InstrumentationKey` is `String.Empty`.

## Expected 

`TelemetryConfiguration.Active.InstrumentationKey` is `ApplicationInsights:InstrumentationKey`.

## Version Info 
SDK Version : 2.6.4
.NET Version : .NET Core 2.0
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) :Console App in Visual Studio Debugger

**Comment by cijothomas** [comment]
@zippy1981 What is the version of application insights sdk you are using? Please try the latest published version 2.3.0 and this issue shouldn't be there.
If you find otherwise, please share a repro project. (also make sure you did set environment variable correctly. I had faced similar issue when i set ENV variable in local session, and start dotnet process from different session!)

let me know what you find.

**Comment by cijothomas** [comment]
I used this command from Admin console to set env variable, and started dotnet app.dll from a new command line after.
`setx ApplicationInsights:InstrumentationKey instrumentationkey /M`

**Comment by zippy1981** [comment]
@cijothomas So by SDK do you mean the Nuget package called Microsoft.ApplicationInsights or Microsoft.ApplicationInsights.AspNetCore?

It doesn't seem to work either way on my machine after updating both nuget packages so I need to dig into the code, and submit a unit test.

[Here is the example code of how I was doing it.](https://github.com/serilog/serilog-sinks-applicationinsights/pull/61/files)

I threw the following in startup.cs:


            services.AddApplicationInsightsTelemetry();

            var expectedInstrumentationKey = Configuration.GetValue<string>("ApplicationInsights:InstrumentationKey");
            if (string.IsNullOrEmpty(TelemetryConfiguration.Active.InstrumentationKey))
            {
                throw new SystemException($"Instrumentation Key should not be blank. Expected: {expectedInstrumentationKey}");
            }

            if (TelemetryConfiguration.Active.InstrumentationKey != "")
            {
                throw new SystemException($"Unexpected Instrumentation Key. Expected: {expectedInstrumentationKey} Actual: {TelemetryConfiguration.Active.InstrumentationKey}");
            }


Please confirm the following be the intended behavior for  `AddApplicationInsightsTelemetry(this IServiceCollection services, IConfiguration configuration)` and  `AddApplicationInsightsTelemetry(this IServiceCollection services)`:

 * Set TelemetryConfiguration.Active
 * Read the instrumentation key from "ApplicationInsights:InstrumentationKey" and "APPLICATION_INSIGHTS_IKEY" with a preference for the former

**Comment by pharring** [comment]
If you're trying to access `TelemetryConfiguration.Active` from within `ConfigureServices`, then I think this is by design.

The key to understanding this is that `services.AddApplicationInsightsTelemetry()` only tells the DI framework how to construct and configure the telemetry pipeline. It doesn't actually build it until some component requests one of the services that needs it. Accessing `TelemetryConfiguration.Active` bypasses DI entirely and forces App Insights (the base SDK) to construct (a minimal, barebones) one for you.

Rule of thumb: Doe not reference `TelemetryConfiguration.Active` in an ASP.NET Core application. It's added as a singleton to the services collection, so get it from there, or let the DI framework pass the value in a public constructor. Note that, once you've got it from the service singleton you _can_ modify it's `InstrumentationKey` property and that will have a global effect.

**Comment by zippy1981** [comment]
Ok I'll close this an open some new issues.

@pharring Unfortunately, in order for me to use Serilog the way I want to (specifically not duplicate the Instrumentation key across my configuration), I need to use `TelemetryConfiguration.Active`. I'm working with them to improve their initialization code ([PR as proof here](https://github.com/serilog/serilog-sinks-applicationinsights/pull/60)). So yes I'm the customer that needs the Singleton property you'd prefer never existed.

Anyway some new discoveries:

* Something else was configuring application insights. I'm not sure what yet, but there is a check in `[services.AddApplicationInsightsTelemetry()](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/6e602f85b1d39d9e779f001297def36b1e935899/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L134)` to see if `ApplicationInsightsDebugLogger` was added to the service collection and if it was, to not configure application insights.
* __Unverified__ Nothing is actually calling TelemetryConfiguration.set_Active() as far as I can tell from the Visual Studio debugger, something is just copying properties over like the instrumentation key. This is of course great if you pass TelemetryConfiguration.Active over to something that later makes a TelemetryClient from it. That gets the proper configuration.


I'm going to offer constructive ideas on how to improve all this is separate issues.

**Comment by lmolkova** [comment]
@zippy1981 
TelemetryConfiguration.Active is configured here:

https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/205bcd90fa70b5afc3f8dd967035bac7b06c00ef/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptions.cs#L50

Active is set in the [base SDK](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/a4a7131c1b54f65679c23fb1cf1cecfca81dae30/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L82) when we first request it.

It happens when the first WebHost in the application is being built.
It configures Active to be identical to the TelemetryConfiguration in the DI services, however they are different instances and if you modify Active, it has no effect on the telemetry that is reported by the SDK automatically.

So, if you want to **modify** configuration - use DI before the TelemetryConfiguration is resolved - you'll get both: Active and one in the DI reflecting your modifications.

If you want only to **access** TelemetryConfiguration - you are welcome to use Active  singleton. 

Hope it helps!
