### ISSUE TITLE
Support for Application Insights without ASP.NET Core

### ISSUE THREAD

**Issue by ChristopherHaws** [Microsoft/ApplicationInsights-aspnetcore#749]
In https://github.com/aspnet/Logging/issues/463 it is mentioned that there is an implementation of `ApplicationInsightsLoggerProvider` that lives [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/tree/17cc5de23ba58872650f7f2c4eaf0f0f2e47a823/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation). This is great if the app is running on ASP.NET Core, but this doesn't take into account other types of apps such as ASP.NET 4 websites or Windows Services.

From what I can see, this code is not dependent on ASP.NET Core. Is there a chance that this logger could be moved to the logging repo as `Microsoft.Extensions.Logging.ApplicationInsights`? Is there a good reason this hasn't been done already?

Thanks!

**Comment by SergeyKanzhelev** [comment]
No good reasons. Interesting timing for the question as I was playing with it over the weekend (https://github.com/Microsoft/ApplicationInsights-dotnet-logging/tree/sergkanz/ILogger/src/ILogger) =). If you want to contribute - it will be great, I will definitely help with reviews. Otherwise - we do not have an ETA for it yet.

**Comment by davidfowl** [comment]
@SergeyKanzhelev I have some requests:
- I'd like it to be using the 2.0 version of logging (this means adding ILoggerBuilder extension methods and potentially dropping the ILoggerFactory extensions).
- I'd like to see the namespace fixed. We could discuss using the Microsoft.Extensions namespace instead of the AI namespace.
- Support for [Scopes](https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/491). We did some work in 2.0 to make it easier for providers to implement scopes. All of the AsyncLocal goop is handled by the factory and we provide 2 interfaces for making the system work:
- [ISupportExternalScope](https://github.com/aspnet/Logging/blob/80a301e89d7933a032969bfdc1c299df280c7d92/src/Microsoft.Extensions.Logging.Abstractions/ISupportExternalScope.cs) and [IExternalScopeProvider](https://github.com/aspnet/Logging/blob/80a301e89d7933a032969bfdc1c299df280c7d92/src/Microsoft.Extensions.Logging.Abstractions/IExternalScopeProvider.cs)

**Comment by ChristopherHaws** [comment]
I would like to contribute to this item. Some questions I have are:

- If no `TelemetryClient` has been registered, should we throw, use a `new TelemetryClient()`, or disable the logger?
- Currently, `ApplicationInsightsLoggerOptions` is in the `Microsoft.ApplicationInsights.AspNetCore.Logging` namespace. If this is moved, that would be a breaking change. How should this be handled?
- I think that naming the namespace `Microsoft.Extensions.Logging.ApplicationInsights` would align the best with the rest of the `ILogger` implementations, but `Microsoft.ApplicationInsights.Logging` could work too. Do you agree with either of these?

**Comment by davidfowl** [comment]
> If no TelemetryClient has been registered, should we throw, use a new TelemetryClient(), or disable the logger?

That should be mostly impossible with these new extension methods in `ILoggerBuilder` since it would just register the required services. It's possible we should consider deprecating the direct ILoggerFactory overloads or just leave them out of this package completely. 

> Currently, ApplicationInsightsLoggerOptions is in the Microsoft.ApplicationInsights.AspNetCore.Logging namespace. If this is moved, that would be a breaking change. How should this be handled?

We need to decide if this package is a clean break or not. I think it should be.

> I think that naming the namespace Microsoft.Extensions.Logging.ApplicationInsights would align the best with the rest of the ILogger implementations, but Microsoft.ApplicationInsights.Logging could work too. Do you agree with either of these?

@Eilon, what do you think about naming this package Microsoft.Extensions.Logging.ApplicationInsights (since its all from the greater Microsoft anyways)?

**Comment by Eilon** [comment]
@davidfowl I'm fine with that, but @damianedwards is the one who would have more say-so. If we go with that option, whoever uploads the package just needs to be aware that the account on nuget.org needs to have the right permissions because it's in a "reserved package namespace".

**Comment by reerden** [comment]
I think this is related to issue #750.

**Comment by RamjotSingh** [comment]
@davidfowl , @SergeyKanzhelev I stumbled across this issue and thought I might give it a try. I picked up Sergey's solution and tried to incorporate David's comments while taking inspiration from [ConsoleLogger](https://github.com/aspnet/Logging/tree/master/src/Microsoft.Extensions.Logging.Console) and [BatchingLogger](https://github.com/aspnet/Logging/blob/master/src/Microsoft.Extensions.Logging.AzureAppServices/Internal/BatchingLoggerProvider.cs).

I have put a pull request https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239. Please take a look and let me know your thoughts.

**Comment by RamjotSingh** [comment]
Updating back here. PR https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239 is now merged and removed the dependency on AspNetCore

**Comment by lmolkova** [comment]
If anyone wants to give it a try, it was just released on myget https://www.myget.org/F/applicationinsights/api/v3/index.json

**Comment by davidfowl** [comment]
@lmolkova should this be closed?

**Comment by cijothomas** [comment]
@davidfowl Yes this can be closed.
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239
