### ISSUE TITLE
Confused by OnInitializeTelemetry parameters

### ISSUE THREAD

**Issue by bragma** [Microsoft/ApplicationInsights-aspnetcore#772]
Hi,
I'm trying to understand what are the parameters passed to OnInitializeTelemetry. In particular, I am confused between the last 2: request and telemetry. I've checked the code of TelemetryInitializerBase but still can't make up my mind, in particular their scope and their content.  I've also checked the implementation of several telemetry initializes in this SDK, but I don't understand why properties are sometimes set on the RequestTelemetry and some  others on the ITelemetry one.
If I need to set some custom properties specific to an http request (scope), where do I have to set them?
Thanks!

**Comment by cijothomas** [comment]
The last 2 parameters are requestTelemetry, and telemetry.
Telemetry - this is the currently telemetry item being tracked and you are trying to enrich it with additional properties.
RequestTelemetry - this is the request telemetry instance under which the other telemetry is reported. This is passed to OnInitializeTelemetry so that the telemetry can be enriched with somethign already populated inside RequestTelemetry.


If your intention is to enrich you request telemetry - simply use a ITelemetryInitializer which does not derive from WebTelemetryInitializerBase.

**Comment by bragma** [comment]
@cijothomas thanks for clarifying things up.
I am actually inheriting from TelemetryInitializerBase because I need to the User from HttpContext and it already implements locking on the context, so actually I am doing something like this:

```
protected override void OnInitializeTelemetry(HttpContext httpContext, RequestTelemetry requestTelemetry, ITelemetry telemetry)
{
	var user = httpContext.User;

	if (telemetry is RequestTelemetry && user != null)
	{
		if (!requestTelemetry.Properties.ContainsKey("PropertyXXX"))
		{
			requestTelemetry.Properties["PropertyXXX"] = user.GetPropertyXXX().ToString();
		}
	}
}
```

It works, I hope it is the correct way to do it.
