### ISSUE TITLE
Configure Application Insights from IApplicationBuilder in AspNet Core project

### ISSUE THREAD

**Issue by DavidFlamme** [microsoft/ApplicationInsights-aspnetcore#830]
## Feature request

It is currently very cumbersome to reconfigure Application Insights in a AspNet Core project. Currently one has to write the following code to add sampling.

    var aiOptions = new ApplicationInsightsServiceOptions();
    aiOptions.EnableAdaptiveSampling = false;
    
    services.AddApplicationInsightsTelemetry(aiOptions);
    
    var configuration = TelemetryConfiguration.Active;
    // Duplicated from TelemetryConfigurationOptionsSetup.AddSampling, but added exception exclusion
    configuration.DefaultTelemetrySink.TelemetryProcessorChainBuilder.UseAdaptiveSampling(5.0, excludedTypes: "Event;Exception");
    configuration.DefaultTelemetrySink.TelemetryProcessorChainBuilder.UseAdaptiveSampling(5.0, includedTypes: "Event");

## Version Info 
SDK Version : AspNet core 2.1
.NET Version : 4.7.2 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : IIS on Azure PaaS

**Comment by cijothomas** [comment]
Thanks for sharing feedback. We are aware of this issue and there are plans to address overall configuration story improvements by mid-2019.

Also the correct way is as per below: (using .Active is not recommended, and also note the change since 2.5.0-beta2)
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream#configure-sampling-settings

**Comment by fschmied** [comment]
Is it planned to support ApplicationInsights.config in ASP.NET Core projects? IMO, it would be very useful if the different project types would be aligned regarding configuration.

**Comment by cijothomas** [comment]
Closing this. We are tracking overall config story improvements separately.
