### ISSUE TITLE
Internal exception when initializing

### ISSUE THREAD

**Issue by jorismathijssen** [microsoft/ApplicationInsights-aspnetcore#915]
## Repro Steps
We have _Microsoft.ApplicationInsights.AspNetCore_ 2.7.1 installed and somehow in our logging we are receiving the error below in our logging. I have read a few posts about this issue but all those post are related to the _Microsoft.ApplicationInsight_ 2.8.x  in combination with azureFunctions. But we don't use both of them.

Could this be an error in my code or is it an internal problem?

##  Actual Behavior
`AI (Internal): [Microsoft-ApplicationInsights-Core] [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer, exception message - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Cookies()
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.UpdateRequestTelemetryFromPlatformContext(RequestTelemetry requestTelemetry, HttpContext platformContext)
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.OnInitializeTelemetry(HttpContext platformContext, RequestTelemetry requestTelemetry, ITelemetry telemetry)
   at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.TelemetryInitializerBase.Initialize(ITelemetry telemetry)
   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]`

## Expected Behavior
We don't want this error flooding our Microsoft.ApplicationInsight logging.

## Version Info 
SDK Version : 2.7.1
.NET Version :	.net Core 2.2.5						
How Application was onboarded with SDK(VisualStudio) :
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) :
IIS

**Comment by lmolkova** [comment]
What kind of application do you have? ASP.NET Core app or something else? 

If you only want to enable logging without other application insights capabilities and don't even run web application, you may use Microsoft.Extensions.Logging.ApplicationInsights instead of Microsoft.ApplicationInsights.AspNetCore. Here is an article about it: https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger

If you still want to track outgoing http calls and other dependencies or other features of AppInsights, you may filter out this errors until the problem is solved on our side.
Here is more info on it: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#adding-telemetry-processors and https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#filtering-itelemetryprocessor

**Comment by jorismathijssen** [comment]
Thank you for the suggestion. For now i will try to filter the exception.
